# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
    remotes:
    - name: nxp
      url-base: https://github.com/NXP
    - name: nxp-zephyr
      url-base: https://github.com/nxp-zephyr
    - name: nxp-mcuxpresso
      url-base: https://github.com/nxp-mcuxpresso
    defaults:
      remote: nxp-mcuxpresso
    group-filter:
    - -optional
    - -bifrost
    - -ble_cs_algo_private
    - -bluetooth_private
    projects:
    - name: bifrost
      path: bifrost
      remote: nxp-zephyr
      revision: main
      west-commands: scripts/west_commands.yml
      groups:
      - bifrost
    - name: mcuxsdk-manifests
      repo-path: mcuxsdk-manifests
      path: manifests
      revision: v25.09.00_RC1
      import: true
    - name: matter
      remote: nxp
      repo-path: matter
      revision: 28bdc7b95586f29f3552832e02ada575f07be374
      path: mcuxsdk/middleware/matter
      submodules:
      - name: nlio
        path: third_party/nlio/repo
      - name: nlassert
        path: third_party/nlassert/repo
      - name: pigweed
        path: third_party/pigweed/repo
      - name: jsoncpp
        path: third_party/jsoncpp/repo
      - name: nxp_matter_support
        path: third_party/nxp/nxp_matter_support
      - name: ot-nxp
        path: third_party/openthread/ot-nxp
    - name: mcu-sdk-examples-matter
      repo-path: mcuxsdk-examples-matter
      path: mcuxsdk/examples/matter_examples
      revision: main