# The west manifest file (west.yml) for MCUXpresso SDK delivery.
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html
manifest:
  remotes:
    - name: nxp
      url-base: https://github.com/NXP
    - name: nxp-zephyr
      url-base: https://github.com/nxp-zephyr
    - name: nxp-mcuxpresso
      url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  group-filter:
    - -optional
    - -bifrost
    - -ble_cs_algo_private
    - -bluetooth_private
  projects:
    - name: bifrost
      path: bifrost
      remote: nxp-zephyr
      revision: main
      west-commands: scripts/west_commands.yml
      groups:
        - bifrost
    - name: core
      path: mcuxsdk/
      repo-path: mcuxsdk-core
      revision: 2656ba11af509b6ab9d8b808f6bfd4f2b95f74c0
      west-commands: scripts/west_commands.yml
    - name: mcu-sdk-components
      repo-path: mcux-component
      path: mcuxsdk/components
      revision: e67b49539b52f6df45d76db4f565da427b007f7b
    - name: secure_storage
      repo-path: secure_storage
      path: mcuxsdk/middleware/secure_storage
      revision: 58a86d061b60fee59495172a760cb7039473d5b0
    - name: psa_crypto_driver
      url: https://github.com/NXP/psa_crypto_driver
      path: mcuxsdk/components/psa_crypto_driver
      revision: 1cf8fd38d1894d4e28053770687641a2e08a0c29
    - name: mcuxsdk-manifests
      repo-path: mcuxsdk-manifests
      path: manifests
      revision: v26.03.00
      import: true
    - name: matter
      remote: nxp
      repo-path: matter
      revision: 0e3285a9a28908e9e8eb8e51679048349cb2dc3b
      path: mcuxsdk/middleware/matter
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: pigweed
          path: third_party/pigweed/repo
        - name: jsoncpp
          path: third_party/jsoncpp/repo
        - name: nxp_matter_support
          path: third_party/nxp/nxp_matter_support
        - name: ot-nxp
          path: third_party/openthread/ot-nxp
        - name: simw-top-mini
          path: third_party/simw-top-mini/repo
        - name: uriparser
          path: third_party/uriparser/repo
    - name: mcu-sdk-examples-matter
      repo-path: mcuxsdk-examples-matter
      path: mcuxsdk/examples/matter_examples
      revision: 75d8b337098f67f863a64fdfd7c34d7dd5e41620
